AllCops:
    Include:
        - '**/Gemfile'
        - Rakefile
        - config.ru
    Exclude:
        - db/**/*
        - bin/**/*
        - sorbet/**/*

Style/FrozenStringLiteralComment:
    Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true

Lint/RaiseException:
    Enabled: true

Style/ExponentialNotation:
    Enabled: true

Style/HashEachMethods:
    Enabled: true

Style/HashTransformValues:
    Enabled: true

Style/SlicingWithRange:
    Enabled: true

Layout/SpaceAroundMethodCallOperator:
    Enabled: true

Lint/StructNewOverride:
    Enabled: true

Style/HashTransformKeys:
    Enabled: true